#!/usr/bin/env python3
"""Regenerate confxml.c/h and compute the correct MAIN_CONFIG_T_SIGNATURE.

Run from the main/config/ directory after editing settings.xml:
    python3 gen_confxml.py

Then update confparser.h with the printed signature value.
"""

import struct
import zlib
import xml.etree.ElementTree as ET
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ── Regenerate confxml.c/h ──────────────────────────────────────────────────

xml_bytes = open(os.path.join(HERE, 'settings.xml'), 'rb').read()
compressed = zlib.compress(xml_bytes, 9)
qt_data = struct.pack('>I', len(xml_bytes)) + compressed

with open(os.path.join(HERE, 'confxml.h'), 'w') as f:
    f.write(f"""// This file is autogenerated by VESC Tool

#ifndef CONFXML_H_
#define CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_MAIN_CONFIG_T__SIZE\t\t{len(qt_data)}

// Variables
extern uint8_t data_main_config_t_[];

// CONFXML_H_
#endif
""")

with open(os.path.join(HERE, 'confxml.c'), 'w') as f:
    f.write('// This file is autogenerated by VESC Tool\n\n')
    f.write('#include "confxml.h"\n\n')
    f.write(f'__attribute__((used)) uint8_t data_main_config_t_[{len(qt_data)}] = {{\n')
    for i in range(0, len(qt_data), 16):
        chunk = qt_data[i:i+16]
        f.write('\t' + ', '.join(f'0x{b:02x}' for b in chunk) + ', \n')
    f.write('};\n')

print(f"confxml.c/h written ({len(qt_data)} bytes compressed)")

# ── Compute MAIN_CONFIG_T_SIGNATURE ────────────────────────────────────────

tree = ET.parse(os.path.join(HERE, 'settings.xml'))
root = tree.getroot()
params_el = root.find('Params')
ser_order = [s.text for s in root.find('SerOrder').findall('ser')]

param_map = {}
for child in params_el:
    p = {
        'type':      int(child.findtext('type')  or 0),
        'vTx':       int(child.findtext('vTx')   or 0),
        'enumNames': [e.text for e in child.findall('enumNames')],
    }
    param_map[child.tag] = p

def crc32c(data: bytes) -> int:
    crc = 0xFFFFFFFF
    for b in data:
        crc ^= b
        for _ in range(8):
            mask = -(crc & 1)
            crc = (crc >> 1) ^ (0x82F63B78 & mask)
    return (~crc) & 0xFFFFFFFF

sig_str = ''
for name in ser_order:
    sig_str += name
    p = param_map.get(name)
    if p:
        sig_str += str(p['type']) + str(p['vTx'])
        for e in p['enumNames']:
            sig_str += e
    else:
        print(f"  WARNING: '{name}' in SerOrder but not in Params")

sig = crc32c(sig_str.encode('utf-8'))
print(f"\nSet in confparser.h:")
print(f"  #define MAIN_CONFIG_T_SIGNATURE  {sig}")
